//! A saved world's two text files: what the world is, and which of its
//! superchunks were hot, cooling and warming.

use type_registry::LayerType;
use coordinates::SuperchunkIndex;
use utilities::csv;

/// The world file's columns.
const WORLD_COLUMNS: [&str; 2] = ["world", "is"];
/// The world file's format, and the number of the one written.
const FORMAT: (&str, &str) = ("format", "2");

/// The name of the kind of entity a world is hot about, in its file.
const HOT_ENTITY: &str = "hot entity";

/// The name of the sheep each superchunk generated in the viewport starts
/// with, in the file of a world whose camera loads superchunks.
const CAMERA_FLOCK: &str = "camera flock";

/// The name of the row of the superchunks still owed their camera flock
/// ([`WorldInfo::without_camera_flock`]): spaces between them.
const WITHOUT_CAMERA_FLOCK: &str = "without camera flock";

/// What starts the name of a number the world is generated by, in its file.
const GENERATION: &str = "generation ";

/// What a world is. Its name is its folder's.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct WorldInfo {
    /// Its seed: what everything generated and drawn comes from.
    pub seed: u64,
    /// The tick it is at: the next to run.
    pub tick: u64,
    /// Its layer types: made hot on every chunk when it is loaded.
    pub layers: Vec<LayerType>,
    /// Superchunks along a side of it, if it has a size: a square
    /// about its origin, nothing ever made outside it.
    pub side: Option<u32>,
    /// Whether every superchunk of it is hot throughout, whatever its
    /// entities do: only one with a size can be.
    pub forced: bool,
    /// The kind of entity it is hot about, if it is not forced hot,
    /// as a number: whoever runs it knows the kinds. None if its file
    /// says none: its runner's own then.
    pub hot_entity: Option<u64>,
    /// If its camera loads superchunks -- the viewport's kept hot, and
    /// generated if never made, as a halo's are -- the sheep each
    /// superchunk generated in the viewport starts with; none if it does not.
    pub camera_flock: Option<u64>,
    /// The superchunks generated out of the camera's view, for a halo
    /// alone, while its camera loads: each still owed its camera flock,
    /// given once the camera sees it. Sorted.
    pub without_camera_flock: Vec<u64>,
    /// How it is generated: numbers, each with its name, kept for
    /// whoever generates it, who knows what they mean -- read back
    /// sorted by name.
    pub generation: Vec<(String, u64)>,
}

impl WorldInfo {
    /// As the world's file holds it: a row a thing the world is, its
    /// name and what it is -- its seed in hexadecimal, its layer types
    /// with spaces between.
    pub(crate) fn to_text(&self) -> String {
        let layers: Vec<String> = self.layers.iter().map(|layer| layer.0.to_string()).collect();
        let mut rows = vec![
            (FORMAT.0.to_string(), FORMAT.1.to_string()),
            ("seed".to_string(), utilities::seed::hex(self.seed)),
            ("tick".to_string(), self.tick.to_string()),
            ("layers".to_string(), layers.join(" ")),
        ];
        rows.extend(self.side.map(|side| ("side".to_string(), side.to_string())));
        rows.extend(self.forced.then(|| ("forced".to_string(), "1".to_string())));
        rows.extend(self.hot_entity.map(|kind| (HOT_ENTITY.to_string(), kind.to_string())));
        rows.extend(self.camera_flock.map(|sheep| (CAMERA_FLOCK.to_string(), sheep.to_string())));
        let owed: Vec<String> = self.without_camera_flock.iter().map(u64::to_string).collect();
        rows.extend((!owed.is_empty()).then(|| (WITHOUT_CAMERA_FLOCK.to_string(), owed.join(" "))));
        rows.extend(self.generation.iter().map(|(name, value)| (format!("{GENERATION}{name}"), value.to_string())));
        csv::row(&WORLD_COLUMNS) + &rows.iter().map(|(name, is)| csv::row(&[name, is])).collect::<String>()
    }

    /// From the world's file's text, or what is wrong with it: its
    /// rows in any order under the one naming the columns, each name
    /// once, a name not known passed over. A row it lacks is as a world
    /// with nothing said of it has it -- the format the one written,
    /// tick 0, no layers, no size, not forced, no hot entity or camera
    /// flock, no generation numbers -- but the seed, which nothing
    /// stands in for: another would make the superchunks not yet made
    /// unlike those that are.
    pub(crate) fn from_text(text: &str) -> Result<Self, String> {
        let mut rows = csv::rows(text).into_iter();
        if rows.next().is_none_or(|columns| columns != WORLD_COLUMNS) {
            return Err(format!("does not start with `{}`", WORLD_COLUMNS.join(",")));
        }
        let mut read = Self { seed: 0, tick: 0, layers: Vec::new(), side: None, forced: false, hot_entity: None, camera_flock: None, without_camera_flock: Vec::new(), generation: Vec::new() };
        let (mut seed, mut named) = (None, Vec::new());
        for row in rows {
            let [key, value] = &row[..] else {
                return Err(format!("`{}` is not a name and what it is", row.join(",")));
            };
            let (key, value) = (key.trim(), value.trim());
            if named.iter().any(|name| name == key) {
                return Err(format!("`{key}` said twice"));
            }
            named.push(key.to_string());
            let number = || value.parse::<u64>().map_err(|_| format!("`{value}` is not a number"));
            match key {
                _ if key == FORMAT.0 && value != FORMAT.1 => return Err(format!("format {value}, not {}", FORMAT.1)),
                _ if key == FORMAT.0 => {}
                "seed" => seed = Some(utilities::seed::of_hex(value).ok_or_else(|| format!("`{value}` is not a seed"))?),
                "tick" => read.tick = number()?,
                "layers" => read.layers = value.split_whitespace().map(|layer| layer.parse().map(LayerType).map_err(|_| format!("`{layer}` is not a layer type"))).collect::<Result<Vec<_>, _>>()?,
                "side" => read.side = Some(value.parse().map_err(|_| format!("`{value}` is not a side"))?),
                "forced" => read.forced = number()? != 0,
                HOT_ENTITY => read.hot_entity = Some(number()?),
                CAMERA_FLOCK => read.camera_flock = Some(number()?),
                WITHOUT_CAMERA_FLOCK => read.without_camera_flock = value.split_whitespace().map(|superchunk| superchunk.parse().map_err(|_| format!("`{superchunk}` is not a superchunk"))).collect::<Result<_, _>>()?,
                _ if key.starts_with(GENERATION) => read.generation.push((key[GENERATION.len()..].to_string(), number()?)),
                // A name of another format: passed over.
                _ => {}
            }
        }
        if read.forced && read.side.is_none() {
            return Err("forced hot, with no side to be hot to".to_string());
        }
        read.seed = seed.ok_or("no seed")?;
        // Sorted by name: whatever their rows' order, the same numbers read the same.
        read.generation.sort_unstable();
        Ok(read)
    }
}

/// The hot file's columns.
const HOT_COLUMNS: [&str; 3] = ["superchunk", "is", "until"];
/// What a superchunk hot and not cooling is, in the hot file.
const HOT: &str = "hot";
/// What a hot superchunk cooling is, in the hot file.
const COOLING: &str = "cooling";
/// What a superchunk warming is, in the hot file.
const WARMING: &str = "warming";

/// Which superchunks a world had hot when saved: made hot again as it is
/// loaded, before it ticks. A row a superchunk: its index in
/// hexadecimal, then `hot`, or `cooling` and the tick it goes cold at
/// if hot and cooling, or `warming` and the tick it turns hot at.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct HotSuperchunks {
    /// The hot superchunks, sorted.
    pub hot: Vec<SuperchunkIndex>,
    /// The hot superchunks cooling, sorted, each with the tick it goes
    /// cold at.
    pub cooling: Vec<(SuperchunkIndex, u64)>,
    /// The superchunks warming, sorted, each with the tick it turns hot
    /// at.
    pub warming: Vec<(SuperchunkIndex, u64)>,
}

impl HotSuperchunks {
    /// As the hot file holds it.
    pub(crate) fn to_text(&self) -> String {
        let cools = |superchunk: &SuperchunkIndex| self.cooling.binary_search_by_key(superchunk, |&(cooling, _)| cooling).ok().map(|at| self.cooling[at].1);
        let index = |superchunk: &SuperchunkIndex| format!("{:011x}", superchunk.0);
        let hot = self.hot.iter().map(|superchunk| match cools(superchunk) {
            Some(tick) => csv::row(&[index(superchunk), COOLING.to_string(), tick.to_string()]),
            None => csv::row(&[index(superchunk), HOT.to_string(), String::new()]),
        });
        let warming = self.warming.iter().map(|(superchunk, tick)| csv::row(&[index(superchunk), WARMING.to_string(), tick.to_string()]));
        std::iter::once(csv::row(&HOT_COLUMNS)).chain(hot).chain(warming).collect()
    }

    /// From the hot file's text, or what is wrong with it.
    pub(crate) fn from_text(text: &str) -> Result<Self, String> {
        let mut rows = csv::rows(text).into_iter();
        if rows.next().is_none_or(|columns| columns != HOT_COLUMNS) {
            return Err(format!("does not start with `{}`", HOT_COLUMNS.join(",")));
        }
        let mut read = Self::default();
        for row in rows {
            let wrong = || format!("`{}` is not a superchunk index, `{HOT}`, `{COOLING}` or `{WARMING}`, and a tick unless hot", row.join(","));
            let [superchunk, is, until] = &row[..] else {
                return Err(wrong());
            };
            let superchunk = SuperchunkIndex(u64::from_str_radix(superchunk.trim(), 16).map_err(|_| wrong())?);
            let tick = || until.trim().parse().map_err(|_| wrong());
            match is.trim() {
                HOT if until.trim().is_empty() => read.hot.push(superchunk),
                COOLING => {
                    read.hot.push(superchunk);
                    read.cooling.push((superchunk, tick()?));
                }
                WARMING => read.warming.push((superchunk, tick()?)),
                _ => return Err(wrong()),
            }
        }
        read.hot.sort_unstable();
        read.cooling.sort_unstable();
        read.warming.sort_unstable();
        Ok(read)
    }
}
