//! The world's halos: the simulation's (`simulation::halos`), lent
//! what the world holds and what generates a superchunk never made --
//! and, if its camera loads superchunks, a flock put on each one
//! generated in the viewport. Which are hot, the viewport's among them,
//! is the simulation's to say, as the world's hot defines it.

use crate::World;
use worldgen::generate_superchunk;
use chunk_storage::jobs::Generate;
use chunk_storage::LayerCodec;
use coordinates::SuperchunkIndex;
use entity_manager::EntityType;
use entity_rules::sheep::SHEEP;
use simulation::halos::{HaloChange, Halos, Held};

/// The hot entity, as a world's halos are told: the kind that
/// matters, about which the world is ticked. For now the sheep -- the
/// only kind there is -- stand in for the people to come.
pub const HOT_ENTITY: EntityType = SHEEP;

impl World {
    /// Has the halos do `work` on what the world holds.
    fn with_halos<Done>(&mut self, work: impl FnOnce(&mut Halos, &mut Held<'_>) -> Done) -> Done {
        let (seed, generation) = (self.info.seed, self.generation);
        let generate = move |superchunk: SuperchunkIndex| -> Generate { Box::new(move |codec: &mut LayerCodec| generate_superchunk(&generation, seed, superchunk).image(codec)) };
        let mut held = Held { arena: &mut self.arena, storage: &mut self.storage, entities: &mut self.entities, simulation: &mut self.simulation, cold: &mut self.cold, layers: &self.info.layers, generate: &generate };
        work(&mut self.halos, &mut held)
    }

    /// Moves the halos to where the hot entities stand, with the
    /// viewport's superchunks (`Halos::move_to_hot_entities`) -- and, if
    /// its camera loads superchunks, puts its camera flock on each
    /// generated by the move in the viewport, and on each generated
    /// earlier out of view that the viewport has reached since. Only in
    /// the viewport: one generated for a halo alone is owed its flock
    /// until the camera sees it, or every flock's halo would generate
    /// superchunks with flocks of their own, and the world grow
    /// without end.
    pub fn move_halos(&mut self) -> HaloChange {
        let change = self.with_halos(|halos, held| halos.move_to_hot_entities(held));
        if let Some(sheep) = self.info.camera_flock.filter(|&sheep| sheep > 0) {
            let generated = self.halos.generated().to_vec();
            self.owe_camera_flocks(&generated);
            // Paid to the hot ones in view: a superchunk still warming is paid once it is hot.
            let viewport = self.halos.viewport();
            let seen: Vec<SuperchunkIndex> = self.info.without_camera_flock.iter().map(|&owed| SuperchunkIndex(owed)).filter(|superchunk| viewport.binary_search(superchunk).is_ok() && self.entities.superchunk(*superchunk).is_some()).collect();
            for &superchunk in &seen {
                self.put_flock(superchunk, sheep as usize);
            }
            if !seen.is_empty() {
                self.info.without_camera_flock.retain(|&owed| seen.binary_search(&SuperchunkIndex(owed)).is_err());
                self.entities.apply();
            }
        }
        change
    }

    /// Keeps `superchunks` as owed their camera flock
    /// (`WorldInfo::without_camera_flock`): generated, and not yet
    /// given one.
    pub(crate) fn owe_camera_flocks(&mut self, superchunks: &[SuperchunkIndex]) {
        let owed = &mut self.info.without_camera_flock;
        owed.extend(superchunks.iter().map(|superchunk| superchunk.0));
        owed.sort_unstable();
        owed.dedup();
    }

    /// Makes `wanted` -- sorted -- the hot superchunks now, none
    /// outside the world's size (`Halos::keep_hot`): what generating
    /// and loading start from.
    pub fn keep_hot(&mut self, wanted: &[SuperchunkIndex]) -> HaloChange {
        self.with_halos(|halos, held| halos.keep_hot(held, wanted))
    }

    /// The superchunks warming, each with the tick it turns hot at.
    pub fn warming(&self) -> impl Iterator<Item = (SuperchunkIndex, u64)> + '_ {
        self.halos.warming()
    }

    /// The hot superchunks cooling, each with the tick it goes cold at.
    pub fn cooling(&self) -> impl Iterator<Item = (SuperchunkIndex, u64)> + '_ {
        self.halos.cooling()
    }

    /// Starts warming `superchunk`, to turn hot at tick `due`.
    pub(crate) fn start_warming(&mut self, superchunk: SuperchunkIndex, due: u64) {
        self.with_halos(|halos, held| halos.start_warming(held, superchunk, due));
    }

    /// Writes back every hot superchunk's changed bitmaps, then
    /// flushes every superchunk with changes in the ring: the cold
    /// pool's images the cells as they are.
    pub fn write_back_and_flush_all(&mut self) {
        self.with_halos(|halos, held| {
            halos.write_back_all(held);
            halos.flush_all(held);
        });
    }
}
