//! The world's halos: the simulation's (`simulation::halos`), lent
//! what the world holds and what generates a superchunk never made --
//! and, if its camera loads superchunks, told those in view, a flock
//! put on each of them generated.

use crate::host::frame::Viewport;
use crate::{generate_image, World};
use chunk_storage::jobs::Generate;
use chunk_storage::LayerCodec;
use coordinates::{SuperchunkIndex, WORLD_SIDE_SUPERCHUNKS};
use entity_manager::EntityType;
use entity_rules::sheep::SHEEP;
use simulation::halos::{HaloChange, Halos, Held};

/// The hot entity, as a world's halos are told: the kind that
/// matters, about which the world is ticked. For now the sheep -- the
/// only kind there is -- stand in for the people to come.
pub const HOT_ENTITY: EntityType = SHEEP;

/// Superchunks along a side of the square in view a camera loads at
/// most, about the view's middle: a view zoomed far out keeps no more
/// than 64 hot for being seen.
pub const CAMERA_SIDE: u32 = 8;

impl World {
    /// Has the halos do `work` on what the world holds.
    fn with_halos<Done>(&mut self, work: impl FnOnce(&mut Halos, &mut Held<'_>) -> Done) -> Done {
        let (seed, generation) = (self.info.seed, self.generation);
        let generate = move |superchunk: SuperchunkIndex| -> Generate { Box::new(move |codec: &mut LayerCodec| generate_image(&generation, seed, superchunk, codec)) };
        let mut held = Held { arena: &mut self.arena, storage: &mut self.storage, entities: &mut self.entities, simulation: &mut self.simulation, cold: &mut self.cold, layers: &self.info.layers, generate: &generate };
        work(&mut self.halos, &mut held)
    }

    /// Moves the halos to where the hot entities stand, with the
    /// superchunks in view (`Halos::move_to_hot_entities`) -- and, if
    /// its camera loads superchunks, puts its camera flock on each
    /// generated by the move while in view. Only those: one generated
    /// for a halo alone starts with nothing, or every flock's halo
    /// would generate superchunks with flocks of their own, and the
    /// world grow without end.
    pub fn move_halos(&mut self) -> HaloChange {
        let change = self.with_halos(|halos, held| halos.move_to_hot_entities(held));
        if let Some(sheep) = self.info.camera_flock.filter(|&sheep| sheep > 0) {
            let in_view = self.halos.in_view();
            let seen: Vec<SuperchunkIndex> = self.halos.generated().iter().copied().filter(|superchunk| in_view.binary_search(superchunk).is_ok()).collect();
            for &superchunk in &seen {
                self.put_flock(superchunk, sheep as usize);
            }
            if !seen.is_empty() {
                self.entities.apply();
            }
        }
        change
    }

    /// Keeps the superchunks in `viewport` hot from the next tick on,
    /// as a halo's are, in place of those in view before -- if the
    /// world's camera loads superchunks: at most [`CAMERA_SIDE`] along
    /// a side, about its middle, and none outside the world.
    pub fn keep_in_view(&mut self, viewport: Viewport) {
        if self.info.camera_flock.is_none() {
            return;
        }
        let span = |first: u32, last: u32| {
            let last = last.min(WORLD_SIDE_SUPERCHUNKS - 1);
            let first = first.min(last);
            let start = ((first + last).div_ceil(2)).saturating_sub(CAMERA_SIDE / 2).max(first);
            start..=last.min(start + CAMERA_SIDE - 1)
        };
        let (across, down) = (span(viewport.first.0, viewport.last.0), span(viewport.first.1, viewport.last.1));
        let in_view = down.flat_map(|y| across.clone().map(move |x| SuperchunkIndex::from_cartesian(x, y))).collect();
        self.halos.keep_in_view(in_view);
    }

    /// Makes `wanted` -- sorted -- the hot superchunks now, none
    /// outside the world's size (`Halos::keep_hot`): what generating
    /// and loading start from.
    pub fn keep_hot(&mut self, wanted: &[SuperchunkIndex]) -> HaloChange {
        self.with_halos(|halos, held| halos.keep_hot(held, wanted))
    }

    /// The superchunks warming, each with the tick it turns hot at.
    pub fn warming(&self) -> impl Iterator<Item = (SuperchunkIndex, u64)> + '_ {
        self.halos.warming()
    }

    /// The hot superchunks cooling, each with the tick it goes cold at.
    pub fn cooling(&self) -> impl Iterator<Item = (SuperchunkIndex, u64)> + '_ {
        self.halos.cooling()
    }

    /// Starts warming `superchunk`, to turn hot at tick `due`.
    pub(crate) fn start_warming(&mut self, superchunk: SuperchunkIndex, due: u64) {
        self.with_halos(|halos, held| halos.start_warming(held, superchunk, due));
    }

    /// Writes back every hot superchunk's changed bitmaps, then
    /// flushes every superchunk with changes in the ring: the cold
    /// pool's images the cells as they are.
    pub(crate) fn write_back_and_flush_all(&mut self) {
        self.with_halos(|halos, held| {
            halos.write_back_all(held);
            halos.flush_all(held);
        });
    }
}
